FROM  ibmcom/mq:latest

#Presetting environment variables
ENV LICENSE=accept
ENV MQ_QMGR_NAME=QM1_SSL
ENV MQ_DEV=true
ENV MQ_ADMIN_PASSWORD=password1
ENV MQ_APP_PASSWORD=password1

SHELL ["/bin/bash", "-c"]

EXPOSE 1414 
EXPOSE 9443
EXPOSE 9157
